import { AppcontextProvider } from "../src/context/Appcontext";
import Head from "next/head";
import { useEffect } from "react";
import { useRouter } from "next/router";
import React from "react";
import "./component/i18n";

function MyApp({ Component, pageProps }: any) {
  const router = useRouter();
  useEffect(() => {
    const token = localStorage.getItem("token");
    if (!token) {
      localStorage.removeItem("userName");
      localStorage.removeItem("Level");
      router.push("/");
    }
  }, []);
  return (
    <AppcontextProvider>
      <Head>
        <title>TIT Company System</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Logo.png" />
      </Head>

      <Component {...pageProps} />
    </AppcontextProvider>
  );
}

export default MyApp;
